# Generated by Django 5.2.9 on 2026-04-07 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('tag_type', models.CharField(choices=[('auto', 'Auto-generated'), ('custom', 'Custom')], default='custom', max_length=10)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of documents using this tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['name'], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AddField(
            model_name='document',
            name='branch',
            field=models.CharField(default='main', help_text='Git branch', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='repository_id',
            field=models.CharField(default='', help_text='Repository identifier', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='unique_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, help_text='Cached document content'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(default='markdown', help_text='Document type', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(help_text='File path in repository', max_length=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wiki.space'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='Document title', max_length=500),
        ),
        migrations.AlterField(
            model_name='space',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(blank=True, help_text='Space description'),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether space is publicly accessible'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(help_text='Display name', max_length=255),
        ),
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('space', 'repository_id', 'path')},
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(blank=True, help_text='External URL if not internal link', max_length=1000)),
                ('link_type', models.CharField(choices=[('internal', 'Internal Link'), ('external', 'External Link'), ('reference', 'Reference')], default='internal', max_length=20)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether link target exists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='wiki.document')),
                ('target_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='wiki.document')),
            ],
            options={
                'verbose_name': 'Document Link',
                'verbose_name_plural': 'Document Links',
            },
        ),
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_uri', models.CharField(db_index=True, help_text='Universal source address', max_length=1000)),
                ('line_start', models.IntegerField(blank=True, help_text='Starting line number (1-indexed)', null=True)),
                ('line_end', models.IntegerField(blank=True, help_text='Ending line number (1-indexed)', null=True)),
                ('text', models.TextField(help_text='Comment text (supports Markdown)')),
                ('thread_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Thread identifier for grouping')),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether comment is resolved')),
                ('anchoring_status', models.CharField(choices=[('anchored', 'Anchored'), ('moved', 'Moved'), ('outdated', 'Outdated')], default='anchored', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wiki.filecomment')),
            ],
            options={
                'verbose_name': 'File Comment',
                'verbose_name_plural': 'File Comments',
                'ordering': ['source_uri', 'line_start', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_url', models.URLField(help_text='Git repository URL', max_length=500)),
                ('branch', models.CharField(default='main', help_text='Branch to sync', max_length=255)),
                ('direction', models.CharField(choices=[('pull_only', 'Pull Only'), ('push_only', 'Push Only'), ('bidirectional', 'Bidirectional')], default='pull_only', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_configs', to='wiki.space')),
            ],
            options={
                'verbose_name': 'Git Sync Config',
                'verbose_name_plural': 'Git Sync Configs',
            },
        ),
        migrations.CreateModel(
            name='UserChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_full_name', models.CharField(help_text='Repository identifier', max_length=255)),
                ('file_path', models.CharField(help_text='File path in repository', max_length=1000)),
                ('original_content', models.TextField(help_text='Original file content')),
                ('modified_content', models.TextField(help_text='Modified file content')),
                ('commit_message', models.TextField(blank=True, help_text='Commit message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('committed', 'Committed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_changes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Change',
                'verbose_name_plural': 'User Changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0, help_text='TF-IDF or manual relevance score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='wiki.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='wiki.tag')),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
                'ordering': ['-relevance_score'],
                'unique_together': {('document', 'tag')},
            },
        ),
    ]
