# Generated by Django 5.2.9 on 2026-04-10 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_tag_alter_document_options_alter_space_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_tree_config', models.JSONField(default=dict, help_text='\n        Configuration for mapping Git file tree to pages.\n        Example: {\n            "root_path": "/docs",\n            "file_extensions": [".md", ".mdx"],\n            "ignore_patterns": ["node_modules", ".git"],\n            "title_from_frontmatter": true,\n            "title_field": "title"\n        }\n        ')),
                ('page_display_config', models.JSONField(default=dict, help_text='\n        Configuration for page display.\n        Example: {\n            "show_breadcrumbs": true,\n            "show_toc": true,\n            "show_last_updated": true,\n            "default_view_mode": "document"\n        }\n        ')),
                ('sync_config', models.JSONField(default=dict, help_text='\n        Configuration for Git sync.\n        Example: {\n            "auto_sync": true,\n            "sync_interval_minutes": 15,\n            "sync_on_webhook": true,\n            "conflict_resolution": "git_wins"\n        }\n        ')),
                ('custom_settings', models.JSONField(default=dict, help_text='Additional custom settings')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Space Configuration',
                'verbose_name_plural': 'Space Configurations',
                'db_table': 'space_configurations',
            },
        ),
        migrations.CreateModel(
            name='SpacePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer - Read only'), ('editor', 'Editor - Can edit pages'), ('admin', 'Admin - Full control')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Space Permission',
                'verbose_name_plural': 'Space Permissions',
                'db_table': 'space_permissions',
            },
        ),
        migrations.CreateModel(
            name='SpaceShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(help_text='ID of the target page')),
                ('label', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Space Shortcut',
                'verbose_name_plural': 'Space Shortcuts',
                'db_table': 'space_shortcuts',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserSpacePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('last_visited_at', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('last_viewed_page_id', models.IntegerField(blank=True, help_text='ID of last viewed page', null=True)),
            ],
            options={
                'verbose_name': 'User Space Preference',
                'verbose_name_plural': 'User Space Preferences',
                'db_table': 'user_space_preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Space', 'verbose_name_plural': 'Spaces'},
        ),
        migrations.AddField(
            model_name='space',
            name='git_base_url',
            field=models.URLField(blank=True, help_text='Git provider base URL', null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='git_default_branch',
            field=models.CharField(default='main', help_text='Default Git branch', max_length=100),
        ),
        migrations.AddField(
            model_name='space',
            name='git_project_key',
            field=models.CharField(blank=True, help_text='Git project key (for Bitbucket)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='git_provider',
            field=models.CharField(blank=True, choices=[('bitbucket_server', 'Bitbucket Server'), ('github', 'GitHub')], help_text='Git provider type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='git_repository_id',
            field=models.CharField(blank=True, help_text='Git repository identifier', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='git_repository_name',
            field=models.CharField(blank=True, help_text='Git repository name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last Git sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(help_text='Space owner with full control', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='page_count',
            field=models.IntegerField(default=0, help_text='Number of pages in this space'),
        ),
        migrations.AddField(
            model_name='space',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private - Only owner and explicitly shared users'), ('team', 'Team - All authenticated users'), ('public', 'Public - Anyone with link')], default='private', help_text='Space visibility level', max_length=20),
        ),
        migrations.AlterField(
            model_name='space',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the space (legacy field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Legacy field - use visibility instead'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(help_text='Display name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['owner', '-updated_at'], name='wiki_space_owner_i_61733d_idx'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['visibility'], name='wiki_space_visibil_e95bb5_idx'),
        ),
        migrations.AddField(
            model_name='spaceconfiguration',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='wiki.space'),
        ),
        migrations.AddField(
            model_name='spacepermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacepermission',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='wiki.space'),
        ),
        migrations.AddField(
            model_name='spacepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spaceshortcut',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shortcuts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spaceshortcut',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='wiki.space'),
        ),
        migrations.AddField(
            model_name='userspacepreference',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='wiki.space'),
        ),
        migrations.AddField(
            model_name='userspacepreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='spacepermission',
            index=models.Index(fields=['user', 'role'], name='space_permi_user_id_f5f754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spacepermission',
            unique_together={('space', 'user')},
        ),
        migrations.AddIndex(
            model_name='userspacepreference',
            index=models.Index(fields=['user', '-last_visited_at'], name='user_space__user_id_931e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='userspacepreference',
            index=models.Index(fields=['user', 'is_favorite'], name='user_space__user_id_4a5730_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userspacepreference',
            unique_together={('user', 'space')},
        ),
    ]
