# Generated by Django 5.2.9 on 2026-04-10 21:38

from django.db import migrations


def populate_space_owners(apps, schema_editor):
    """
    Populate the owner field from created_by for existing spaces.
    """
    Space = apps.get_model('wiki', 'Space')
    for space in Space.objects.all():
        if space.created_by and not space.owner:
            space.owner = space.created_by
            space.save(update_fields=['owner'])


def reverse_populate_space_owners(apps, schema_editor):
    """
    Reverse migration - clear owner field.
    """
    Space = apps.get_model('wiki', 'Space')
    Space.objects.all().update(owner=None)


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_add_space_enhancements'),
    ]

    operations = [
        migrations.RunPython(populate_space_owners, reverse_populate_space_owners),
    ]
