# Generated by Django 5.2.9 on 2026-04-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_populate_space_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(db_index=True, help_text='Machine identifier (e.g., total_pages, health_score)', max_length=100)),
                ('field_name', models.CharField(help_text='Human-readable label (e.g., "Total Pages", "Health Score")', max_length=200)),
                ('field_value_str', models.TextField(blank=True, help_text='String/JSON/enum value', null=True)),
                ('field_value_int', models.BigIntegerField(blank=True, help_text='Integer or boolean (0/1) value', null=True)),
                ('field_value_float', models.FloatField(blank=True, help_text='Fractional numeric value', null=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True, help_text='When this attribute was collected/computed')),
                ('data_source', models.CharField(blank=True, default='', help_text='Source discriminator (e.g., git_sync, manual, computed)', max_length=100)),
                ('version', models.BigIntegerField(default=0, help_text='Version number for deduplication')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='wiki.space')),
            ],
            options={
                'verbose_name': 'Space Attribute',
                'verbose_name_plural': 'Space Attributes',
                'db_table': 'space_attributes',
                'indexes': [models.Index(fields=['space', 'field_id'], name='space_attri_space_i_2fde4f_idx'), models.Index(fields=['field_id', 'collected_at'], name='space_attri_field_i_122289_idx'), models.Index(fields=['data_source'], name='space_attri_data_so_04e790_idx')],
                'unique_together': {('space', 'field_id', 'version')},
            },
        ),
    ]
