# Generated by Django 5.2.9 on 2026-04-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_add_space_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='git_base_url',
            field=models.CharField(blank=True, help_text='Git provider base URL or filesystem path for local Git', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='git_provider',
            field=models.CharField(blank=True, choices=[('bitbucket_server', 'Bitbucket Server'), ('github', 'GitHub'), ('local_git', 'Local Git Repository')], help_text='Git provider type', max_length=50, null=True),
        ),
    ]
