# Generated by Django 5.2.9 on 2026-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_add_local_git_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='git_default_branch',
            field=models.CharField(blank=True, default='', help_text='Default Git branch (auto-detected if empty)', max_length=100),
        ),
    ]
