# Generated by Django 5.2.9 on 2026-04-11 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_space_git_default_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
