# Generated by Django 5.2.9 on 2026-04-14 19:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_alter_document_id_alter_documentlink_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Relative path in repository (e.g., docs/README.md)', max_length=1000)),
                ('is_folder', models.BooleanField(default=False, help_text='True if this is a folder, False for files')),
                ('is_visible', models.BooleanField(default=True, help_text='Show in Documents mode')),
                ('display_name', models.CharField(blank=True, help_text='Custom display name (if not auto-extracted)', max_length=500, null=True)),
                ('display_name_source', models.CharField(choices=[('custom', 'Custom Name'), ('filename', 'Use Filename'), ('first_h1', 'First H1 Header'), ('first_h2', 'First H2 Header'), ('title_frontmatter', 'Title from Frontmatter')], default='first_h1', help_text='Method for determining display name', max_length=50)),
                ('extracted_name', models.CharField(blank=True, help_text='Cached extracted name from file content', max_length=500, null=True)),
                ('extracted_at', models.DateTimeField(blank=True, help_text='When the name was last extracted', null=True)),
                ('sort_order', models.IntegerField(blank=True, help_text='Custom sort order (null = auto)', null=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon name', max_length=10, null=True)),
                ('apply_to_children', models.BooleanField(default=False, help_text='Apply this configuration to all children (folders only)')),
                ('is_override', models.BooleanField(default=False, help_text='True if this mapping overrides parent folder rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_mappings', to=settings.AUTH_USER_MODEL)),
                ('parent_rule', models.ForeignKey(blank=True, help_text='Parent folder rule (if inherited)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_mappings', to='wiki.filemapping')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mappings', to='wiki.space')),
            ],
            options={
                'verbose_name': 'File Mapping',
                'verbose_name_plural': 'File Mappings',
                'db_table': 'wiki_file_mapping',
                'indexes': [models.Index(fields=['space', 'is_visible'], name='wiki_file_m_space_i_29b9ff_idx'), models.Index(fields=['space', 'file_path'], name='wiki_file_m_space_i_321740_idx'), models.Index(fields=['space', 'is_folder'], name='wiki_file_m_space_i_ea97f2_idx')],
                'unique_together': {('space', 'file_path')},
            },
        ),
    ]
