# Generated by Django 5.2.9 on 2026-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_add_file_mapping_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='filters',
            field=models.JSONField(blank=True, default=list, help_text='File extension/pattern filters (e.g., [".md", ".xml"])'),
        ),
    ]
