# Generated by Django 5.2.9 on 2026-04-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_space_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='default_display_name_source',
            field=models.CharField(choices=[('first_h1', 'First H1'), ('first_h2', 'First H2'), ('title_frontmatter', 'Title from Frontmatter'), ('filename', 'Filename'), ('custom', 'Custom')], default='first_h1', help_text='Default display name source for all files in this space', max_length=50),
        ),
    ]
