# Generated by Django 5.2.9 on 2026-04-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_space_default_display_name_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemapping',
            name='children_display_name_source',
            field=models.CharField(blank=True, choices=[('first_h1', 'First H1 Header'), ('first_h2', 'First H2 Header'), ('title_frontmatter', 'Title from Frontmatter'), ('filename', 'Use Filename')], help_text='Default display name source for children (folders only)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filemapping',
            name='display_name_source',
            field=models.CharField(choices=[('custom', 'Custom Name'), ('filename', 'Use Filename'), ('first_h1', 'First H1 Header'), ('first_h2', 'First H2 Header'), ('title_frontmatter', 'Title from Frontmatter')], default='first_h1', help_text='Method for determining display name for this item', max_length=50),
        ),
    ]
