# Generated by Django 5.2.9 on 2026-04-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_filemapping_children_display_name_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemapping',
            name='effective_display_name_source',
            field=models.CharField(blank=True, help_text='Computed display name source after inheritance resolution', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filemapping',
            name='effective_is_visible',
            field=models.BooleanField(default=True, help_text='Computed visibility after inheritance resolution'),
        ),
    ]
