# Generated by Django 5.2.9 on 2026-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_filemapping_effective_display_name_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemapping',
            name='display_name_source',
            field=models.CharField(blank=True, choices=[('custom', 'Custom Name'), ('filename', 'Use Filename'), ('first_h1', 'First H1 Header'), ('first_h2', 'First H2 Header'), ('title_frontmatter', 'Title from Frontmatter')], help_text='Method for determining display name for this item (null = inherit from parent or space default)', max_length=50, null=True),
        ),
    ]
