# Generated by Django 5.2.9 on 2026-04-20 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_remove_display_name_source_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='edit_fork_project_key',
            field=models.CharField(blank=True, help_text='Project key for edit fork (e.g., ~doclab-service)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='edit_fork_repo_slug',
            field=models.CharField(blank=True, help_text='Repository slug for edit fork', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='edit_fork_ssh_url',
            field=models.CharField(blank=True, help_text='SSH clone URL for edit fork (e.g., ssh://git@git.example.com/~service/repo.git)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='EditSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft - Changes pending'), ('submitting', 'Submitting - PR being created'), ('submitted', 'Submitted - PR created'), ('merged', 'Merged'), ('closed', 'Closed without merge'), ('abandoned', 'Abandoned by user'), ('error', 'Error during submission')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if status is ERROR')),
                ('pending_changes', models.JSONField(default=list, help_text='\n        List of pending file changes:\n        [\n            {\n                "file_path": "docs/README.md",\n                "original_content": "...",\n                "modified_content": "...",\n                "change_type": "modify",\n                "description": "Fixed typo"\n            }\n        ]\n        ')),
                ('branch_name', models.CharField(blank=True, help_text='Branch name on edit fork (e.g., doclab/maxim-cherey/edit-abc123)', max_length=200, null=True)),
                ('base_branch', models.CharField(default='master', help_text='Base branch to create PR against', max_length=100)),
                ('commit_sha', models.CharField(blank=True, help_text='SHA of the commit on the edit fork', max_length=40, null=True)),
                ('pr_id', models.IntegerField(blank=True, help_text='Pull request ID in Bitbucket', null=True)),
                ('pr_url', models.URLField(blank=True, help_text='URL to the pull request', max_length=500, null=True)),
                ('title', models.CharField(help_text='Session title / PR title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Session description / PR description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the PR was created', null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='wiki.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edit Session',
                'verbose_name_plural': 'Edit Sessions',
                'db_table': 'wiki_edit_session',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='wiki_edit_s_user_id_207517_idx'), models.Index(fields=['space', 'status'], name='wiki_edit_s_space_i_af4879_idx'), models.Index(fields=['user', 'space', 'status'], name='wiki_edit_s_user_id_a7940f_idx')],
            },
        ),
    ]
