# Generated by Django 5.2.9 on 2026-04-20 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_edit_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSessionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path relative to repo root', max_length=500)),
                ('change_type', models.CharField(choices=[('modify', 'Modify existing file'), ('create', 'Create new file'), ('delete', 'Delete file')], default='modify', max_length=20)),
                ('original_content', models.TextField(blank=True, help_text='Original file content (empty for create)')),
                ('modified_content', models.TextField(blank=True, help_text='Modified file content (empty for delete)')),
                ('description', models.CharField(blank=True, help_text='Description of this change', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft - Not yet committed'), ('staged', 'Staged - Committed to fork'), ('submitted', 'Submitted - In PR'), ('merged', 'Merged'), ('discarded', 'Discarded')], default='draft', max_length=20)),
                ('commit_sha', models.CharField(blank=True, help_text='SHA of the commit containing this change', max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staged_at', models.DateTimeField(blank=True, help_text='When the change was committed to fork', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='wiki.editsession')),
            ],
            options={
                'verbose_name': 'Edit Session Change',
                'verbose_name_plural': 'Edit Session Changes',
                'db_table': 'wiki_edit_session_change',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='wiki_edit_s_session_d7db08_idx'), models.Index(fields=['file_path'], name='wiki_edit_s_file_pa_da8b2a_idx'), models.Index(fields=['status'], name='wiki_edit_s_status_fd2f62_idx')],
                'unique_together': {('session', 'file_path')},
            },
        ),
    ]
