# Generated by Django 5.2.9 on 2026-04-20 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_add_edit_session_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(help_text='Branch name on edit fork', max_length=200)),
                ('base_branch', models.CharField(default='master', help_text='Base branch to create PR against', max_length=100)),
                ('last_commit_sha', models.CharField(blank=True, help_text='SHA of the last commit on this branch', max_length=40, null=True)),
                ('pr_id', models.IntegerField(blank=True, help_text='Pull request ID', null=True)),
                ('pr_url', models.URLField(blank=True, help_text='URL to the pull request', max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active - Has staged changes'), ('pr_open', 'PR Open'), ('pr_merged', 'PR Merged'), ('pr_closed', 'PR Closed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_branches', to='wiki.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Branch',
                'verbose_name_plural': 'User Branches',
                'db_table': 'wiki_user_branch',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'space'], name='wiki_user_b_user_id_7ebe73_idx'), models.Index(fields=['status'], name='wiki_user_b_status_2c1971_idx')],
                'unique_together': {('user', 'space', 'branch_name')},
            },
        ),
        migrations.CreateModel(
            name='UserDraftChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path relative to repo root', max_length=500)),
                ('change_type', models.CharField(choices=[('modify', 'Modify existing file'), ('create', 'Create new file'), ('delete', 'Delete file')], default='modify', max_length=20)),
                ('original_content', models.TextField(blank=True, help_text='Original file content (empty for create)')),
                ('modified_content', models.TextField(blank=True, help_text='Modified file content (empty for delete)')),
                ('description', models.CharField(blank=True, help_text='Description of this change', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_changes', to='wiki.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Draft Change',
                'verbose_name_plural': 'User Draft Changes',
                'db_table': 'wiki_user_draft_change',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'space'], name='wiki_user_d_user_id_dd2a7a_idx'), models.Index(fields=['file_path'], name='wiki_user_d_file_pa_699b24_idx')],
                'unique_together': {('user', 'space', 'file_path')},
            },
        ),
    ]
