# Generated by Django 5.2.9 on 2026-04-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_add_user_draft_change_and_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='edit_fork_local_path',
            field=models.CharField(blank=True, help_text='Local path to pre-cloned edit fork repo (for development, overrides ssh_url)', max_length=500, null=True),
        ),
    ]
