# Generated by Django 5.2.9 on 2026-04-07 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('bitbucket_server', 'Bitbucket Server')], help_text='Git provider type', max_length=50)),
                ('base_url', models.URLField(help_text='Base URL for the Git provider (e.g., https://api.github.com or https://bitbucket.example.com)', max_length=500)),
                ('encrypted_token', models.TextField(help_text='Encrypted access token')),
                ('encrypted_username', models.TextField(blank=True, help_text='Encrypted username (for Bitbucket Server)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Git Token',
                'verbose_name_plural': 'Git Tokens',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'provider', 'base_url')},
            },
        ),
    ]
