[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = src
testpaths = src/unit_tests src/integration_tests
addopts = 
    --reuse-db
    --nomigrations
