# Generated by Django 5.2.9 on 2026-04-07 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the token (e.g., "CLI Access", "CI/CD")', max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer'), ('guest', 'Guest')], default='viewer', help_text='User role for permission management', max_length=20)),
                ('sso_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('last_sso_login', models.DateTimeField(blank=True, null=True)),
                ('settings', models.JSONField(default=dict, help_text='User preferences and settings (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.CharField(help_text='Repository identifier (e.g., "projectkey_reposlug")', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Repository',
                'verbose_name_plural': 'Favorite Repositories',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'repository_id')},
            },
        ),
        migrations.CreateModel(
            name='RecentRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.CharField(max_length=255)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recent Repository',
                'verbose_name_plural': 'Recent Repositories',
                'ordering': ['-last_viewed_at'],
                'unique_together': {('user', 'repository_id')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryViewMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.CharField(max_length=255)),
                ('view_mode', models.CharField(choices=[('developer', 'Developer Mode'), ('document', 'Document Mode')], default='document', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_view_modes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repository View Mode',
                'verbose_name_plural': 'Repository View Modes',
                'unique_together': {('user', 'repository_id')},
            },
        ),
    ]
