# Generated by Django 5.2.9 on 2026-04-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_apitoken_id_alter_favoriterepository_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponseCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(help_text='Provider type (github, bitbucket_server, etc.)', max_length=50)),
                ('provider_id', models.CharField(help_text='Provider identifier (e.g., github.com, bitbucket.example.com)', max_length=255)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP method', max_length=10)),
                ('params_hash', models.CharField(help_text='SHA256 hash of request parameters', max_length=64)),
                ('params_json', models.JSONField(default=dict, help_text='Request parameters (repo, branch, file path, etc.)')),
                ('response_data', models.JSONField(help_text='Cached response data')),
                ('status_code', models.IntegerField(default=200, help_text='HTTP status code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit_count', models.IntegerField(default=0, help_text='Number of times this cache entry was used')),
                ('user', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='api_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Response Cache',
                'verbose_name_plural': 'API Response Caches',
                'indexes': [models.Index(fields=['user', 'provider_type', 'provider_id', 'endpoint', 'params_hash'], name='users_apire_user_id_3d86f3_idx'), models.Index(fields=['user', 'created_at'], name='users_apire_user_id_6296d7_idx')],
                'unique_together': {('user', 'provider_type', 'provider_id', 'endpoint', 'method', 'params_hash')},
            },
        ),
    ]
