# Generated by Django 5.2.9 on 2026-04-09 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("jira", "JIRA"), ("zta", "Zero Trust Access")],
                        help_text="Service type (JIRA, ZTA, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for the service (e.g., https://jira.acme.com) - not required for ZTA",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "encrypted_token",
                    models.TextField(help_text="Encrypted access token"),
                ),
                (
                    "encrypted_username",
                    models.TextField(
                        blank=True,
                        help_text="Encrypted username/email (for JIRA)",
                        null=True,
                    ),
                ),
                (
                    "header_name",
                    models.CharField(
                        blank=True,
                        help_text="Custom header name for ZTA token (e.g., X-Auth-Token, Authorization)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive name for this token",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Token",
                "verbose_name_plural": "Service Tokens",
                "ordering": ["-created_at"],
                "unique_together": {("user", "service_type", "base_url")},
            },
        ),
    ]
