# Generated by Django 5.2.9 on 2026-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_tokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetoken",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("bitbucket_server", "Bitbucket Server"),
                    ("jira", "JIRA"),
                    ("zta", "Zero Trust Access"),
                ],
                help_text="Service type (JIRA, ZTA, etc.)",
                max_length=50,
            ),
        ),
    ]
