# Generated by Django 5.2.9 on 2026-04-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_tokens", "0002_alter_servicetoken_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicetoken",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL for the service (e.g., https://jira.acme.com) - not required for custom header tokens",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="encrypted_username",
            field=models.TextField(
                blank=True,
                help_text="Encrypted username/email (for JIRA and Git providers)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="header_name",
            field=models.CharField(
                blank=True,
                help_text="Custom header name for token (e.g., X-Auth-Token, X-API-Key, Authorization)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicetoken",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("bitbucket_server", "Bitbucket Server"),
                    ("jira", "JIRA"),
                    ("custom_header", "Custom Header Token"),
                ],
                help_text="Service type (Git providers, JIRA, Custom Header, etc.)",
                max_length=50,
            ),
        ),
    ]
