# Generated by Django 5.2.9 on 2026-04-11 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tokens', '0003_rename_zta_to_custom_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
