# Generated by Django 5.2.9 on 2026-04-15 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_tokens', '0004_alter_servicetoken_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicetoken',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='servicetoken',
            constraint=models.UniqueConstraint(condition=models.Q(('service_type', 'custom_header')), fields=('user', 'service_type', 'base_url', 'header_name'), name='unique_custom_header_per_user'),
        ),
        migrations.AddConstraint(
            model_name='servicetoken',
            constraint=models.UniqueConstraint(condition=models.Q(('service_type', 'custom_header'), _negated=True), fields=('user', 'service_type', 'base_url'), name='unique_service_token_per_user'),
        ),
    ]
